COGNITO_DOMAIN = "https://your-cognito-domain.auth.region.amazoncognito.com"
CLIENT_ID = "your-client-id"
REDIRECT_URI = "https://your-app.streamlit.app"
DDB_TABLE = "GradingSubmissions"


SIGNED_URL_API = "https://your-api.execute-api.region.amazonaws.com/prod/get-signed-url"


