[github]
github_token="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"

[apigateway]
signed_url_api="https://orr7xjr63m.execute-api.ap-northeast-1.amazonaws.com/dev/GenerateUrl"
DASHBOARD_API_URL="https://abc123xyz.execute-api.us-east-1.amazonaws.com/prod/dashboard/status"
status_api_url="https://abc123xyz.execute-api.us-east-1.amazonaws.com/prod/dashboard/status"

[cognito]
COGNITO_DOMAIN=""
CLIENT_ID=""
REDIRECT_URI=""
