[github]
github_token="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"

[apigateway]
signed_url_api="https://abc123xyz.execute-api.us-east-1.amazonaws.com/prod/dashboard/status"
DASHBOARD_API_URL="https://abc123xyz.execute-api.us-east-1.amazonaws.com/prod/dashboard/status"

[cognito]
COGNITO_DOMAIN=""
CLIENT_ID=""
REDIRECT_URI=""
