
[github]
github_token="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"

[apigateway]
signed_url_api1="https://orr7xjr63m.execute-api.ap-northeast-1.amazonaws.com/dev/GenerateUrl"
signed_url_api="https://orr7xjr63m.execute-api.ap-northeast-1.amazonaws.com/dev/GenerateUrl"
DASHBOARD_API_URL1="https://u8w3qqosk4.execute-api.ap-northeast-1.amazonaws.com/prod/status"
DASGBOARD_API_URL="https://u8w3qqosk4.execute-api.ap-northeast-1.amazonaws.com/prod/status"
status_api_url1="https://u8w3qqosk4.execute-api.ap-northeast-1.amazonaws.com/prod/status"
status_api_url="https://u8w3qqosk4.execute-api.ap-northeast-1.amazonaws.com/prod/status"

[cognito]
COGNITO_DOMAIN=""
CLIENT_ID=""
REDIRECT_URI=""
=--------